/**
 * Public Sharing Service
 *
 * Generates shareable public URLs for AI research, deep dives, and charts.
 * Each shared item gets a unique ID + stores a snapshot of the content.
 */

export interface SharedResearch {
  id: string;
  userId: string;
  type: "ai_summary" | "deep_dive" | "chart_analysis" | "portfolio_insight";
  title: string;
  ticker: string | null;
  content: string;           // The AI-generated content (markdown)
  metaDescription: string;   // For OG tags
  chartData: unknown | null; // Optional chart snapshot
  viewCount: number;
  createdAt: string;
}

/* ── In-memory store (production → PostgreSQL) ── */

const shareStore = new Map<string, SharedResearch>();
let shareCounter = 0;

function generateShareId(): string {
  const chars = "abcdefghijklmnopqrstuvwxyz0123456789";
  const timestamp = Date.now().toString(36);
  let random = "";
  for (let i = 0; i < 4; i++) {
    random += chars[Math.floor(Math.random() * chars.length)];
  }
  return `${timestamp}${random}`;
}

/**
 * Create a shareable public link for AI research.
 */
export function createShare(input: {
  userId: string;
  type: SharedResearch["type"];
  title: string;
  ticker: string | null;
  content: string;
  metaDescription?: string;
  chartData?: unknown;
}): SharedResearch {
  const id = generateShareId();
  const share: SharedResearch = {
    id,
    userId: input.userId,
    type: input.type,
    title: input.title,
    ticker: input.ticker,
    content: input.content,
    metaDescription:
      input.metaDescription ||
      input.content.replace(/[#*_`]/g, "").slice(0, 160),
    chartData: input.chartData ?? null,
    viewCount: 0,
    createdAt: new Date().toISOString(),
  };
  shareStore.set(id, share);
  shareCounter++;
  return share;
}

/**
 * Get a shared research item by ID (and increment view count).
 */
export function getShare(id: string): SharedResearch | null {
  const share = shareStore.get(id);
  if (!share) return null;
  share.viewCount++;
  return share;
}

/**
 * Get share without incrementing views (for internal use).
 */
export function peekShare(id: string): SharedResearch | null {
  return shareStore.get(id) ?? null;
}

/**
 * Get all shares by a user.
 */
export function getUserShares(userId: string): SharedResearch[] {
  return [...shareStore.values()]
    .filter((s) => s.userId === userId)
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

/**
 * Seed a demo share for development.
 */
export function seedDemoShare(): SharedResearch {
  const existing = shareStore.get("demo-nvda");
  if (existing) return existing;

  const demo = createShare({
    userId: "demo",
    type: "deep_dive",
    title: "NVIDIA (NVDA) — AI Infrastructure Deep Dive",
    ticker: "NVDA",
    content: `# NVIDIA Deep Dive: The AI Infrastructure Play

## Investment Thesis
NVIDIA is the dominant supplier of AI training and inference hardware. With datacenter revenue growing 112% YoY and gross margins at 76.8%, the company is in a uniquely strong position.

## Key Metrics
| Metric | Value | vs Sector |
|--------|-------|-----------|
| Revenue Growth (YoY) | 78% | Outperforms |
| Gross Margin | 76.8% | Best-in-class |
| Datacenter Revenue | $21.2B | 112% YoY |
| Free Cash Flow | $18.9B | Record |
| Forward P/E | 35x | Premium |

## Bull Case
- AI infrastructure buildout is early innings — management guidance of $40-42B next quarter exceeds consensus by 8%
- CUDA ecosystem creates deep software moat
- Gross margins sustaining 75-77% despite Blackwell ramp

## Bear Case
- Custom silicon from hyperscalers could erode TAM
- 35x forward P/E leaves no room for execution missteps
- Supply normalization could remove artificial scarcity premium

## AI Confidence Score
**Directional: Bullish (72% confidence)**
Based on earnings momentum, technical setup, and options flow alignment.

---
*Generated by Obsidian Markets AI • ${new Date().toLocaleDateString()}*`,
    metaDescription:
      "NVIDIA deep dive: AI infrastructure play with 78% revenue growth, 76.8% gross margins. Bull and bear case analysis.",
  });

  // Override the ID to be predictable
  shareStore.delete(demo.id);
  demo.id = "demo-nvda";
  shareStore.set("demo-nvda", demo);
  return demo;
}
